port: ":8080"

middleware_config:
  auth_apikey:
    valid_keys:
      - "abc-123"
      - "dwe-569"

services:
  - name: "user-service"
    route_pattern: "/users"
    urls:
      - "http://localhost:8081"
      - "http://localhost:8083"
    middleware: ["auth_apikey"]

  - name: "product-service"
    route_pattern: "/product"
    urls:
      - "http://localhost:8082"
    middleware: ["auth_apikey"]
